#!/bin/bash
# =============================================================================
# Setup Environment Script for Terraform/Terragrunt
# =============================================================================
# This script helps you set up the required environment variables.
# Run: source scripts/setup-env.sh
# =============================================================================

set -e

INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${INFRA_DIR}/infrastructure/.env"

echo "🔧 Setting up Terraform/Terragrunt environment..."
echo ""

# -----------------------------------------------------------------------------
# GitHub Token (from gh CLI)
# -----------------------------------------------------------------------------
if command -v gh &> /dev/null && gh auth status &> /dev/null; then
    GITHUB_TOKEN=$(gh auth token)
    echo "✅ GitHub token retrieved from gh CLI"
else
    echo "⚠️  GitHub CLI not authenticated. Please run: gh auth login"
    read -p "Enter GitHub token manually: " GITHUB_TOKEN
fi

# -----------------------------------------------------------------------------
# Cloudflare Credentials
# -----------------------------------------------------------------------------
echo ""
echo "📡 Cloudflare Configuration"
echo "   To get your API token:"
echo "   1. Go to: https://dash.cloudflare.com/profile/api-tokens"
echo "   2. Create Token → Edit zone DNS (template)"
echo "   3. Zone Resources: Include → Specific zone → academind.ir"
echo ""

if command -v wrangler &> /dev/null; then
    # Try to get from wrangler if authenticated
    if wrangler whoami &> /dev/null 2>&1; then
        echo "✅ Wrangler is authenticated"
    fi
fi

# Check if we have existing values
if [ -f "$ENV_FILE" ]; then
    source "$ENV_FILE" 2>/dev/null || true
fi

if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
    read -p "Enter Cloudflare API Token: " CLOUDFLARE_API_TOKEN
fi

if [ -z "$CLOUDFLARE_ZONE_ID" ]; then
    echo ""
    echo "   To get Zone ID: Cloudflare Dashboard → academind.ir → Overview (right sidebar)"
    read -p "Enter Cloudflare Zone ID: " CLOUDFLARE_ZONE_ID
fi

# -----------------------------------------------------------------------------
# Registry Credentials (for GitHub Actions secrets)
# -----------------------------------------------------------------------------
echo ""
echo "🐳 Container Registry Credentials"
echo "   These will be injected into GitHub Actions secrets"
echo ""

if [ -z "$REGISTRY_USER" ]; then
    read -p "Enter Registry Username [admin]: " REGISTRY_USER
    REGISTRY_USER=${REGISTRY_USER:-admin}
fi

if [ -z "$REGISTRY_PASSWORD" ]; then
    read -s -p "Enter Registry Password: " REGISTRY_PASSWORD
    echo ""
fi

# -----------------------------------------------------------------------------
# SSH Key (optional - for deployment)
# -----------------------------------------------------------------------------
echo ""
if [ -z "$SSH_PRIVATE_KEY" ]; then
    DEFAULT_KEY="$HOME/.ssh/id_rsa"
    if [ -f "$DEFAULT_KEY" ]; then
        read -p "Use SSH key from $DEFAULT_KEY? [Y/n]: " USE_DEFAULT
        if [ "${USE_DEFAULT,,}" != "n" ]; then
            SSH_PRIVATE_KEY=$(cat "$DEFAULT_KEY" | base64 -w 0)
            echo "✅ SSH key loaded and base64 encoded"
        fi
    else
        echo "⚠️  No default SSH key found. Skipping SSH_PRIVATE_KEY."
    fi
fi

# -----------------------------------------------------------------------------
# Write .env file
# -----------------------------------------------------------------------------
cat > "$ENV_FILE" << EOF
# =============================================================================
# Environment Variables for Terraform/Terragrunt
# =============================================================================
# Generated by: scripts/setup-env.sh
# Date: $(date -Iseconds)
# =============================================================================

# Cloudflare Configuration
export CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN}"
export CLOUDFLARE_ZONE_ID="${CLOUDFLARE_ZONE_ID}"

# GitHub Configuration
export GITHUB_TOKEN="${GITHUB_TOKEN}"

# Container Registry Credentials
export REGISTRY_USER="${REGISTRY_USER}"
export REGISTRY_PASSWORD="${REGISTRY_PASSWORD}"

# SSH Configuration (base64 encoded)
export SSH_PRIVATE_KEY="${SSH_PRIVATE_KEY}"
EOF

chmod 600 "$ENV_FILE"

echo ""
echo "✅ Environment file created: $ENV_FILE"
echo ""
echo "To use:"
echo "  source $ENV_FILE"
echo "  cd infrastructure/live/development"
echo "  terragrunt run-all init"
echo "  terragrunt run-all plan"
echo ""

# Export for current session
export CLOUDFLARE_API_TOKEN
export CLOUDFLARE_ZONE_ID
export GITHUB_TOKEN
export REGISTRY_USER
export REGISTRY_PASSWORD
export SSH_PRIVATE_KEY

echo "✅ Variables exported to current session"
